name: dy_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5-dev

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^3.1.0
  path_provider: ^1.1.2
  flutter_screenutil: ^0.5.3
  flutter_swiper: ^1.0.6
  flutter_bloc: ^0.20.0
  rxdart: ^0.22.0
  equatable: ^0.3.0
  dio: ^2.1.8
  dio_http_cache: ^0.1.4
  chewie: ^0.9.7
  image_picker: ^0.6.1
  flutter_webview_plugin: ^0.3.7
  #flutter_statusbarcolor: ^0.2.1
  pull_to_refresh: ^1.5.5
  web_socket_channel: ^1.0.15
  shared_preferences: ^0.5.3
  wave: ^0.0.8
  cached_network_image: ^1.1.1

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/pic-default.jpg
    - images/back.webp
    - images/default-avatar.webp
    - images/shayuniang.png
    - images/search.webp
    - images/isLive.png
    - images/next.png
    - images/hot.png
    - images/member.png
    - images/play.png
    - images/gift.png
    - images/gift-banner.png
    - images/gift-x.png
    - images/gift-1.png
    - images/float-icon.webp
    - images/init_logo.webp
    - images/init_icon.png
    - images/show-area.webp

    - images/login/syn.webp
    - images/login/qq.webp
    - images/login/wx.webp
    - images/login/weibo.webp
    - images/login/close.webp
    - images/login/safe.webp
    - images/login/member.webp
    - images/login/lock.webp

    - images/head/dylogo.png
    - images/head/camera.webp
    - images/head/chat.webp
    - images/head/game.webp
    - images/head/history.webp
    - images/head/chat-gray.webp
    - images/head/game-gray.webp
    - images/head/history-gray.webp

    - images/lv/3.png
    - images/lv/30.png
    - images/lv/50.png
    - images/lv/80.png

    - images/nav/nav-11.jpg
    - images/nav/nav-21.jpg
    - images/nav/nav-31.jpg
    - images/nav/nav-41.jpg
    - images/nav/nav-51.jpg
    - images/nav/nav-12.jpg
    - images/nav/nav-22.jpg
    - images/nav/nav-32.jpg
    - images/nav/nav-42.jpg
    - images/nav/nav-52.jpg

    - images/bar/hot-chat.jpg
    - images/bar/day-title.png
    - images/bar/hot-title.png
    - images/bar/pull-icon.webp
    - images/bar/usefulSelect.webp
    - images/bar/girl.webp
    - images/bar/boy.webp
    - images/bar/tab-0.png
    - images/bar/tab-1.png
    - images/bar/tab-2.png
    - images/bar/chat-add.jpg
    - images/bar/chat-share.jpg
    - images/bar/chat-star.jpg
    - images/bar/chat-star-act.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
